version: 0.0
os: linux
files:
  - source: /dist/EmployeeDirectory-Angular/
    destination: /var/www/html/  # Path where the Angular app should be served
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
