version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.10.0  # Correctly specify the Node.js version
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building Angular project"
      - ng build --prod
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/employee_directory'  # Replace with your output folder name
